# Generated by Django 5.2 on 2025-04-10 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('JPY', 'Japanese Yen (¥)'), ('INR', 'Indian Rupee (₹)'), ('KES', 'Kenyan Shilling (KSh)'), ('NGN', 'Nigerian Naira (₦)'), ('ZAR', 'South African Rand (R)'), ('GHS', 'Ghanaian Cedi (GH₵)'), ('EGP', 'Egyptian Pound (E£)'), ('MAD', 'Moroccan Dirham (MAD)'), ('TZS', 'Tanzanian Shilling (TSh)'), ('UGX', 'Ugandan Shilling (USh)'), ('XOF', 'West African CFA Franc (CFA)'), ('XAF', 'Central African CFA Franc (FCFA)')], default='USD', max_length=3),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
